### ISSUE TITLE
v1.0 Road Map

### ISSUE THREAD

**Issue by gausby** [gausby/bencode#5]
The project has been stable for quite some time, and I have been using it in various projects without any failures or incorrect behaviour. Still I would like this before slapping the v1.0.0 label on the project.
- [ ] Look through the specs, are they correct?
- [ ] Add documentation to all the modules, especially the user facing `Bencode` module
- [ ] Make a quickcheck model that creates a really, _really_ deep map with numbers, maps, and strings to make double sure that the bencoder works with really deep and big input data
- [ ] Make the quickcheck-ci badge show green on in the readme (I am waiting for quviq to make it possible to run the newest Elixir on quickcheck-ci. That service expect Erlang 16)
